system:
  webserver:
    flask_secret_key: 5yrp7hk261jw8j6oho3sdy5e39lxartm
    sessionstore: /sessions
    emailfrom: raknop@lbl.gov
    smtpserver: smtp.lbl.gov
    smtpport: 25
    smtpusessl: False
    smtpusername: NULL
    smtppassword: NULL

  db:
    postgres_host: postgres
    postgres_port: 5432
    postgres_database: roman_snpit
    postgres_username: postgres
    postgres_password: hj0lhfp2w9bg
    # These next two are for debugging purposes and should always be false in production
    echoqueries: false
    alwaysexplain: false
