---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: romansnpit-rknop-dev
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-romansnpit-rknop-dev-postgres
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        nersc.gov/collab_uids: "101320"
        nersc.gov/gid: "101320"
        nersc.gov/gids: 101320,96414
        nersc.gov/roles: user
        nersc.gov/uid: "95089"
        nersc.gov/username: raknop
      labels:
        workload.user.cattle.io/workloadselector: deployment-romansnpit-rknop-dev-postgres
    spec:
      affinity: {}
      containers:
      - env:
        - name: POSTGRES_DATA_DIR
          value: /var/lib/postgresql/data
        image: registry.nersc.gov/m4385/snpit-db-postgres:rknop-dev-20260204
        imagePullPolicy: Always
        name: postgres
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - CHOWN
            - DAC_OVERRIDE
            - FOWNER
            - SETGID
            - SETUID
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres
        - mountPath: /dev/shm
          name: dshm
        - mountPath: /secrets
          name: secrets
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: registry-nersc
      initContainers:
      - name: volume-mount-hack
        image: busybox
        imagePullPolicy: Always
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        command: [ "sh", "-c", "chown 100:102 /pgdata" ]
        volumeMounts:
        - name: postgres
          mountPath: /pgdata
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: postgres
        persistentVolumeClaim:
          claimName: postgres-pvc
      - emptyDir:
          medium: Memory
          sizeLimit: 128Gi
        name: dshm
      - name: secrets
        secret:
          defaultMode: 292
          optional: false
          secretName: secrets
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: romansnpit-rknop-dev
spec:
  clusterIP: None
  clusterIPs:
  - None
  ports:
  - name: default
    port: 42
    protocol: TCP
    targetPort: 42
  selector:
    workload.user.cattle.io/workloadselector: deployment-romansnpit-rknop-dev-postgres
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
