apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dehydrated-pvc
  namespace: romansnpit-ricksim-smdc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 16Mi
  storageClassName: nfs-client-vast
  volumeMode: Filesystem
