name: Run SNAPPL Tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    name: run snappl tests in docker container
    runs-on: ubuntu-latest

    steps:
      - name: Dump docker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v2

      - name: checkout code
        uses: actions/checkout@v5
        with:
          path: main
          submodules: recursive

      - name: run ruff
        uses: astral-sh/ruff-action@v3
          
      - name: checkout photometry test data
        uses: actions/checkout@v5
        with:
          repository: Roman-Supernova-PIT/photometry_test_data
          path: photometry_test_data

      - name: lfs pull photometry test data
        run: |
          git lfs install --local
          AUTH=$(git config --local http.${{ github.server_url }}/.extraheader)
          git config --local --unset http.${{ github.server_url }}/.extraheader
          git config --local http.${{ github.server_url }}/${{ github.repository }}.git/info/lfs/objects/batch.extraheader "$AUTH"
          git lfs pull
        working-directory: photometry_test_data

      - name: log into github container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: cleanup
        run: |
          # try to save HDD space on the runner by removing some unneeded stuff
          # ref: https://github.com/actions/runner-images/issues/2840#issuecomment-790492173
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: pull environment archive
        run: |
          cd /home/runner/work/snappl
          git clone https://github.com/Roman-Supernova-PIT/environment.git


      - name: pull docker images
        run: |
          cd /home/runner/work/snappl/environment/test-docker-environment
          docker compose pull mailhog postgres webserver shell

      - name: run test
        run: |
          cd /home/runner/work/snappl/environment/test-docker-environment
          docker compose up -d webserver shell
          docker compose exec shell bash -c 'cd /home/snappl && pip install -e .[test]'
          docker compose exec shell bash -c 'cd /home/snpit_utils/tests && pytest -v'
          docker compose down -v
